# Generated by Django 6.0 on 2026-09-14 22:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_enrolled_centers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeLoginLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رمز الدخول')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_links', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رابط دخول لمرة واحدة',
                'verbose_name_plural': 'روابط الدخول',
            },
        ),
    ]
